#!/bin/sh

# we end up with some odd permissions from the image creation,
# and sshd won't accept the pubkey if root doesn't own /root
chown -R root:root /root

echo "nanobox" > /etc/hostname
echo "127.0.0.1    localhost nanobox" > /etc/hosts

chown -R jenkins:jenkins /var/lib/jenkins
chown -R jenkins:jenkins /var/cache/jenkins
chown -R jenkins:jenkins /var/log/jenkins

exec /sbin/init
